version: '3'
services:
  ingredient-microservice-1:
#    image: dbitca785/ingredient_service:test_1

    build: ./PAD_Laboratories-main/Ingredient-microservice/
    container_name: ingredient-microservice-1
    restart: unless-stopped
    depends_on:
      - service_discovery
      - db
    ports:
      - 9191:9191
    networks:
      pad-net:
        ipv4_address: 192.168.0.91
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/ingredients?createDatabaseIfNotExist=true
      spring.datasource.username: postgres
      spring.datasource.password: postgrespass
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.database: postgresql
      spring.jpa.hibernate.ddl-auto : create
      spring.jpa.show-sql : true
      server.address: ingredient-microservice-1
      server.port: 9191
      service.discovery.url: http://service_discovery:8001/
      spring.application.name: ingredient-microservice-1

  ingredient-microservice-2:
#    image: dbitca785/ingredient_service:test_2
    build: ./PAD_Laboratories-main/Ingredient-microservice/
    container_name: ingredient-microservice-2
    restart: unless-stopped
    depends_on:
      - service_discovery
      - db
    ports:
      - 9192:9192
    networks:
      pad-net:
        ipv4_address: 192.168.0.92
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/ingredients?createDatabaseIfNotExist=true
      spring.datasource.username: postgres
      spring.datasource.password: postgrespass
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.database: postgresql
      spring.jpa.hibernate.ddl-auto : create
      spring.jpa.show-sql : true
      server.address: ingredient-microservice-2
      server.port: 9192
      service.discovery.url: http://service_discovery:8001/
      spring.application.name: ingredient-microservice-2

  recipe-microservice:
#    image: dbitca785/recipe_service:latest
    build: ./PAD_Laboratories_secondary/Ingredient-microservice/
    container_name: recipe-microservice
    restart: unless-stopped
    depends_on:
      - service_discovery
      - db
    ports:
      - 8081:8081
    networks:
      pad-net:
        ipv4_address: 192.168.0.69
    environment:
      spring.datasource.url : jdbc:postgresql://db:5432/recipes
      spring.datasource.username : postgres
      spring.datasource.password : postgrespass
      spring.jpa.database: postgresql
      spring.jpa.hibernate.ddl-auto : create
      spring.jpa.show-sql : true
      server.address: recipe-microservice
      server.port: 8081
      service.discovery.url: http://service_discovery:8001/
      spring.application.name: recipe-microservice

#  recipe-microservice-2:
#    #    image: dbitca785/recipe_service:latest
#    build: ./PAD_Laboratories_secondary/Ingredient-microservice/
#    container_name: recipe-microservice-2
#    restart: unless-stopped
#    depends_on:
#      - service_discovery
#      - db
#    ports:
#      - 8083:8083
#    networks:
#      pad-net:
#        ipv4_address: 192.168.0.69
#    environment:
#      spring.datasource.url : jdbc:postgresql://db:5432/recipes
#      spring.datasource.username : postgres
#      spring.datasource.password : postgrespass
#      spring.jpa.database: postgresql
#      spring.jpa.hibernate.ddl-auto : create
#      spring.jpa.show-sql : true
#      server.address: recipe-microservice-2
#      server.port: 8082
#      service.discovery.url: http://service_discovery:8001/
#      spring.application.name: recipe-microservice-2


  gateway:
#      image: gateway:test_1
      build: ./Python_Gateway/
      container_name: gateway
      restart: unless-stopped
      depends_on:
        - service_discovery
        - ingredient-microservice-1
        - ingredient-microservice-2
        - recipe-microservice
#        - recipe-microservice-2
      ports:
        - 5000:5000
      environment:
        DISCOVERY_URL: http://service_discovery:8001
        INGREDIENT_MICROSERVICE_URL1: http://ingredient-microservice-1:9191
        INGREDIENT_MICROSERVICE_URL2: http://ingredient-microservice-2:9192
        RECIPE_MICROSERVICE_URL: http://recipe-microservice:8081
#        RECIPE_MICROSERVICE_URL2: http://recipe-microservice-2:8082
      networks:
        pad-net:
          ipv4_address: 192.168.0.50


  service_discovery:
#    image: service-discovery:test_1
    build: ./Python_Service_Discovery/
    container_name: service_discovery
    restart: unless-stopped
    ports:
      - 8001:8001
    networks:
      pad-net:
        ipv4_address: 192.168.0.81

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: recipes
    ports:
      - 5432:5432
    networks:
      pad-net:
        ipv4_address: 192.168.0.54


  prometheus:
    image: prom/prometheus:v2.47.2
    depends_on:
      - ingredient-microservice-1
      - ingredient-microservice-2
      - recipe-microservice
#      - recipe-microservice-2
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      pad-net:

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      pad-net:

networks:
  pad-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
